# Generated by Django 4.1 on 2022-09-09 03:34
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
